# Decomposing elastic constants

This example provides an illustration of the implementation of the decomposition of elastic constants following the approach of Browaeys and Chevrot (2004). Stishovite elastic constants are used as for the example. The implementation closely follows that in MSAT (Walker and Wookey, 2012) and decomposition follows three stages. First, the input elastic constants are rotated such that the axes lie along high symmetry directions. Second, the matrix is decomposed into contributions for each symmetry. Third, the magnitude of each symmetry component is calculated. 

### References

J. T. Browaeys and S. Chevrot. Decomposition of the elastic tensor and geophysical applications. Geophysical Journal International, 159:667 – 678, 2004.

A. M. Walker and J. Wookey. MSAT – a new toolkit for the analysis of elastic and seismic anisotropy. Computers and Geosciences, 49:81 – 90, 2012.

In [1]:
# Module imports etc
import sys
sys.path.append('..')
import numpy as np

In [2]:
# We need to import decompose and rotate
import pytasa.decompose
import pytasa.rotate


## Setup the input

Here we use the elastic constants of stishovite, but we rotate them in an arbitary way so that the symmetry is not obvious.

In [3]:
stishovite_cij = np.array([[453.0, 211.0, 203.0,   0.0,   0.0,   0.0],
                           [211.0, 453.0, 203.0,   0.0,   0.0,   0.0],
                           [203.0, 203.0, 776.0,   0.0,   0.0,   0.0],
                           [  0.0,   0.0,   0.0, 252.0,   0.0,   0.0],
                           [  0.0,   0.0,   0.0,   0.0, 252.0,   0.0],
                           [  0.0,   0.0,   0.0,   0.0,   0.0, 302.0]])

print("Stishovite elastic constants:")
print(np.array_str(stishovite_cij, precision=1, suppress_small=True))

# Rotate around three axes
stishovite_cij = pytasa.rotate.rot_3(stishovite_cij, 20, 30, 40)
stishovite_rho = 4290.0

print("Rotated stishovite elastic constants:")
print(np.array_str(stishovite_cij, precision=1, suppress_small=True))

Stishovite elastic constants:
[[ 453.  211.  203.    0.    0.    0.]
 [ 211.  453.  203.    0.    0.    0.]
 [ 203.  203.  776.    0.    0.    0.]
 [   0.    0.    0.  252.    0.    0.]
 [   0.    0.    0.    0.  252.    0.]
 [   0.    0.    0.    0.    0.  302.]]
Rotated stishovite elastic constants:
[[ 635.    87.3  150.9   77.6    1.6  -20.6]
 [  87.3  679.3  200.6   31.8  -13.4  -14.9]
 [ 150.9  200.6  724.2   35.2  -24.2   10.6]
 [  77.6   31.8   35.2  250.4   13.9   -8.6]
 [   1.6  -13.4  -24.2   13.9  213.2   58.3]
 [ -20.6  -14.9   10.6   -8.6   58.3  164.1]]


## Find the high symmetry oritentation
This works by computing the Voigt stiffness tensor and dilational stiffness tensor from the input elastic constants tensor (represented as a matrix using Voigt notation). For high symmetry materials the eigenvectors allign. The number of distinct eigenvalues provides information about the symmetry. 

In [4]:
cij_on_axes, rotation_matrix = pytasa.decompose.axes(stishovite_cij)
print("Elastic constants matrix alligned with symmetry directions:")
print(np.array_str(cij_on_axes, precision=1, suppress_small=True))

FIXME: need to issue a warning
Elastic constants matrix alligned with symmetry directions:
[[ 592.2   71.8  203.    -0.    -0.   -76.3]
 [  71.8  592.2  203.     0.    -0.    76.3]
 [ 203.   203.   776.     0.    -0.    -0. ]
 [  -0.     0.     0.   252.     0.    -0. ]
 [  -0.    -0.     0.    -0.   252.    -0. ]
 [ -76.3   76.3    0.    -0.    -0.   162.8]]


# FIXME! - this is clearly wrong!

## Decompose and calculate norms
Project the rotated matrix into isotropic, hexagonal, tetragonal, orthorhombic, monoclinic and triclinic components, then calculate the norms.

In [5]:
decomposed = pytasa.decompose.decompose(cij_on_axes)

In [6]:
# FIXME: this is a bit rubbish
norms = pytasa.decompose.norms(cij_on_axes, decomposed[0], decomposed[1], decomposed[2], 
                               decomposed[3], decomposed[4], decomposed[5])

In [7]:
print(norms)

ElasticNorms(isotropic=0.76694217270623366, hexagonal=0.058050715699155098, tetragonal=0.027521562819149636, orthorhombic=0.0, monoclinic=0.14748554877546138, triclinic=1.1102230246251565e-16)
